### ISSUE TITLE
freebox-transmission-traffic Error

### ISSUE THREAD

**Issue by titithebad** [chteuchteu/Freebox-OS-munin#11]
Hello,

I have this error : Unknown API error "insufficient_rights" on URI http://mafreebox.freebox.fr/api/v3/downloads/stats/ (endpoint downloads/stats/). Plus, we could not print the error message correctly.

Why ?

Regards

**Comment by chteuchteu** [comment]
Hello,

Which Freebox do you own?
Is it up to date?
Did you follow the stepthrough described in the readme?

**Comment by titithebad** [comment]
It seems to work now. I should have forgotten to do _main.py authorize_.

I will give you now tomorrow.

I have a Freebox Revolution

**Comment by chteuchteu** [comment]
Great to know it worked! You can debug the authorization from the Freebox OS's settings page if needed.
Closing this, don't hesitate to reopen it if you're still experiencing troubles with authorization

**Comment by titithebad** [comment]
No it is OK for the authorization.

I should close it tomorrow after testing.

**Comment by chteuchteu** [comment]
> It seems to work now.

Thought it was, my bad. Reopening it in the meantime

**Comment by titithebad** [comment]
The value is always 0.0 ! Why ?

**Comment by titithebad** [comment]
up !

**Comment by chteuchteu** [comment]
Are you getting any errors when running `munin-run freebox-transmission-traffic`?
Is there any useful information in `/var/log/munin/munin-node.log` log file?

Do you have active tasks on the Freebox OS's downloads app?

**Comment by titithebad** [comment]
No error.

No active tasks.

Is the reason ?

**Comment by chteuchteu** [comment]
Yes indeed: the `freebox-transmission-traffic` logs the upload & download rates of the Freebox OS's downloads app. The latter internally uses transmission (a torrent open-source software), hence the plugin name.

If you don't have any active (seeding or downloading) tasks, this plugin will obviously track null (0.00) rates. If you have active tasks, the graph will look something like this:

![](https://github.com/chteuchteu/Freebox-OS-munin/raw/master/doc/freebox_transmission_traffic-day.png)

**Comment by titithebad** [comment]
OK !

**Comment by chteuchteu** [comment]
Closing this issue, please reopen it if you still have questions!
