### ISSUE TITLE
freebox-df retourne 0.0

### ISSUE THREAD

**Issue by Owned67** [chteuchteu/Freebox-OS-munin#12]
` ./main.py authorize
Authorizing...
Waiting for you to push the "Yes" button on your Freebox
..............
Successfully authenticated script. Exiting.`
`chmod 0600 ./freebox.json`
`service munin-node restart`
`munin-run freebox-df
disque_dur.value 0.0`

La valeur pour hddspin n'est pas correct il me semble ?
`munin-run freebox-hddspin
st9250311cs.value 1
st9250311cs_down.value 0
`

ls -all:
`lrwxrwxrwx 1 root root    30 nov.  19 23:11 freebox-df -> /root/Freebox-OS-munin/main.py
lrwxrwxrwx 1 root root    30 nov.  19 23:11 freebox-hddspin -> /root/Freebox-OS-munin/main.py
lrwxrwxrwx 1 root root    30 nov.  19 23:11 freebox-transmission-tasks -> /root/Freebox-OS-munin/main.py
lrwxrwxrwx 1 root root    30 nov.  19 23:11 freebox-transmission-traffic -> /root/Freebox-OS-munin/main.py`

log munin-update.log:

> 2017/11/19 23:15:06 [INFO] creating rrd-file for freebox_transmission_traffic->rx_rate: '/var/lib/munin/localdomain/localhost.localdomain-freebox_transmission_traffic-rx_rate-g.rrd'
2017/11/19 23:15:06 [INFO] creating rrd-file for freebox_transmission_traffic->rx_throttling: '/var/lib/munin/localdomain/localhost.localdomain-freebox_transmission_traffic-rx_throttling-g.rrd'
2017/11/19 23:15:06 [INFO] creating rrd-file for freebox_transmission_traffic->tx_rate: '/var/lib/munin/localdomain/localhost.localdomain-freebox_transmission_traffic-tx_rate-g.rrd'
2017/11/19 23:15:06 [INFO] creating rrd-file for freebox_transmission_traffic->tx_throttling: '/var/lib/munin/localdomain/localhost.localdomain-freebox_transmission_traffic-tx_throttling-g.rrd'
2017/11/19 23:15:07 [INFO] creating rrd-file for freebox_hddspin->st9250311cs: '/var/lib/munin/localdomain/localhost.localdomain-freebox_hddspin-st9250311cs-g.rrd'
2017/11/19 23:15:07 [INFO] creating rrd-file for freebox_hddspin->st9250311cs_down: '/var/lib/munin/localdomain/localhost.localdomain-freebox_hddspin-st9250311cs_down-g.rrd'
2017/11/19 23:15:09 [INFO] creating rrd-file for freebox_transmission_tasks->nb_tasks_downloading: '/var/lib/munin/localdomain/localhost.localdomain-freebox_transmission_tasks-nb_tasks_downloading-g.rrd'
2017/11/19 23:15:09 [INFO] creating rrd-file for freebox_transmission_tasks->nb_tasks_checking: '/var/lib/munin/localdomain/localhost.localdomain-freebox_transmission_tasks-nb_tasks_checking-g.rrd'
2017/11/19 23:15:09 [INFO] creating rrd-file for freebox_transmission_tasks->nb_tasks_stopped: '/var/lib/munin/localdomain/localhost.localdomain-freebox_transmission_tasks-nb_tasks_stopped-g.rrd'
2017/11/19 23:15:09 [INFO] creating rrd-file for freebox_transmission_tasks->nb_tasks_error: '/var/lib/munin/localdomain/localhost.localdomain-freebox_transmission_tasks-nb_tasks_error-g.rrd'
2017/11/19 23:15:09 [INFO] creating rrd-file for freebox_transmission_tasks->nb_tasks_stopping: '/var/lib/munin/localdomain/localhost.localdomain-freebox_transmission_tasks-nb_tasks_stopping-g.rrd'
2017/11/19 23:15:09 [INFO] creating rrd-file for freebox_transmission_tasks->nb_tasks_queued: '/var/lib/munin/localdomain/localhost.localdomain-freebox_transmission_tasks-nb_tasks_queued-g.rrd'
2017/11/19 23:15:09 [INFO] creating rrd-file for freebox_transmission_tasks->nb_tasks_done: '/var/lib/munin/localdomain/localhost.localdomain-freebox_transmission_tasks-nb_tasks_done-g.rrd'
2017/11/19 23:15:09 [INFO] creating rrd-file for freebox_transmission_tasks->nb_tasks_seeding: '/var/lib/munin/localdomain/localhost.localdomain-freebox_transmission_tasks-nb_tasks_seeding-g.rrd'
2017/11/19 23:15:09 [INFO] creating rrd-file for freebox_transmission_tasks->nb_tasks_repairing: '/var/lib/munin/localdomain/localhost.localdomain-freebox_transmission_tasks-nb_tasks_repairing-g.rrd'
2017/11/19 23:15:09 [INFO] creating rrd-file for freebox_transmission_tasks->nb_tasks_extracting: '/var/lib/munin/localdomain/localhost.localdomain-freebox_transmission_tasks-nb_tasks_extracting-g.rrd'
2017/11/19 23:15:10 [INFO] creating rrd-file for freebox_df->disque_dur: '/var/lib/munin/localdomain/localhost.localdomain-freebox_df-disque_dur-g.rrd'
2017/11/19 23:15:10 [WARNING] Service netstat on localhost.localdomain/127.0.0.1:4949 returned no data for label active
2017/11/19 23:15:13 [INFO] Remaining workers: localdomain;localhost.localdomain
2017/11/19 23:15:23 [INFO] Remaining workers: localdomain;localhost.localdomain
2017/11/19 23:15:28 [INFO]: Munin-update finished for node localdomain;localhost.localdomain (26.21 sec)
2017/11/19 23:15:28 [INFO] Reaping Munin::Master::UpdateWorker<localdomain;localhost.localdomain>.  Exit value/signal: 0/0
2017/11/19 23:15:28 [INFO]: Munin-update finished (26.41 sec)

Rien d'anormal dans munin-node.log.

Freebox V6

Merci pour la correction.

**Comment by chteuchteu** [comment]
Ça dépend - est-ce que le disque dur est en veille ? Si c'est le cas, la valeur est correcte

Pour tester, il suffit de copier un très gros fichier (qui prendra plus de 10 minutes à copier pour réellement voir un pic sur le graph), ou de programmer un enregistrement TV (qui entraînera une activité DD le temps de l'enregistrement)

**Comment by Owned67** [comment]
ah d'accord... Merci de l'information. Le player est off donc logique.
