### ISSUE TITLE
Do not store freebox.json in git

### ISSUE THREAD

**Issue by LudovicRousseau** [chteuchteu/Freebox-OS-munin#15]
I think it is a bad idea to store the file `freebox.json` in git.
A new version will be generated for each user and the file will be different from upstream and marked as changed by git. That is annoying.

I propose to remove the file from git, or rename it `freebox.json.example`.

**Comment by tikismoke** [comment]
It's already in the .gitignore no?

So it should not been re-uploaded I think.

**Comment by LudovicRousseau** [comment]
Yes, it is in the `.gitignore`. But it is also in the git repository. 
If you modify it then `git diff` and `git status` will show it.

**Comment by LudovicRousseau** [comment]
My main problem with the `freebox.json` file is that it is marked as changed and so I can't use `git rebase` without using `git stash` first.

**Comment by LudovicRousseau** [comment]
And using `git stash`resets the access rights of the file. So munin-node silently fails. Grrr!
I removed the file in my fork.

**Comment by chteuchteu** [comment]
+1. Removing the file from the repo would make git ask users to revert or stash their changes to this file when pulling the latest changes, so their config wouldn't be deleted.
@LudovicRousseau : do you mind opening a PR? :-)
