### ISSUE TITLE
freebox_connection should be in bits instead of bytes

### ISSUE THREAD

**Issue by ruliane** [chteuchteu/Freebox-OS-munin#23]
_freebox_connection_ is labeled `bytes in (-) / out (+) per second`, though values reported are in bits, not in bytes. Label should be `bits in (-) / out (+) per second`

**Comment by chteuchteu** [comment]
Nice catch, thanks! Could you open a pull request to fix this please?

**Comment by chteuchteu** [comment]
Closed by #24
