### ISSUE TITLE
FB 4K

### ISSUE THREAD

**Issue by airvb** [chteuchteu/Freebox-OS-munin#3]
Testé sur FreeBox 4K  --> Ca fonctionne !

Serait il envisageable d'avoir un graph pour les erreurs FEC, CRC etc etc ? 

Good Job !

**Comment by chteuchteu** [comment]
Bon, y'a plus qu'à renommer le repo ! :')
J'ajoute une indication sur le README concernant la compatibilité avec la Freebox 4K, merci pour le retour !

Les attributs [fec et crc de l'objet XdslStats](http://dev.freebox.fr/sdk/os/connection/#xdsl-stats-object-unstable) ne sont pas documentés sur l'API Freebox OS...
J'imagine qu'ils correspondent au nombre d'erreurs FEC et CRC pour le point courant ? Il suffirait donc de les additionner pour obtenir le nombre d'erreurs sur 5 minutes (entre deux exécutions de munin-update)

On pourrait donc créer un graph xdsl-errors regroupant les différents types d'erreurs. Quels attributs de XdslStats seraient à inclure ? (fec, crc, hec, es, ses ?)

**Comment by airvb** [comment]
J'ai eu un pb de ligne ( avec perte de débit ) récemment du à une perturbation d'une alimentation vieillotte d'un appareil branché sur la même série de prise que la FB .
Le technicien Free qui est venu , a branché son appareil . Et c'est en détectant l'augmentation des erreurs qu'on a pu faire le diagnostic.
Les erreurs FEC , sont sont celles qui sont résolues automatiquement ( ça doit quelque chose du genre parity check ) . Elles ne devraient pas exploser en valeur si la ligne est ok
Les CRC /HEC , si elles augmentent démontrent un pb de ligne physique, et une baisse  de débit 
J'ai pas eu d'info sur les ES/SES
Amha, si j'étais compétent pour le faire j'ajouterai 2 graphes , un pour les montant/ l'autre pour le descendant en incluant les 5 types d'erreurs .
Après les échelles ne sont pas les mêmes . est il possible d'avoir deux échelles différentes en f() du  type d'erreur ...

Merci

**Comment by chteuchteu** [comment]
J'ai créé le mode freebox-xdsl-errors (il est disponible dans la dernière version du script) : 

![freebox_xdsl_errors-day](https://cloud.githubusercontent.com/assets/1551971/18271079/97aaf130-7430-11e6-9f7f-97e4bebc8ae1.png)

J'y ai regroupé tous les types - up et down - sans perdre de lisibilité (les types sont triés par ordre sous le graph)
Il n'y a malheureusement pas la possibilité de modifier l'échelle selon le field... Par contre, on peut définir des seuils d'alertes différents pour chaque field. L'inconvénient est qu'il faudra redémarrer la Freebox pour faire disparaître l'alerte (vu que les valeurs ne feront qu'augmenter).

Est-ce que ce graph répond à votre besoin initial ?

**Comment by chteuchteu** [comment]
Je ferme cette issue étant donné que le graph a été ajouté, n'hésitez pas à commenter et à la rouvrir si besoin !
