### ISSUE TITLE
authorize failure

### ISSUE THREAD

**Issue by tikismoke** [chteuchteu/Freebox-OS-munin#6]
Hi chteuchteu, I got this error.

It's an LXC container from debian 7 with very little little system.

```
root@munin:/home/Freebox-OS-munin# ./main.py authorize
Traceback (most recent call last):
  File "./main.py", line 26, in <module>
    from freebox import app_version, api_authorize, get_freebox
  File "/home/Freebox-OS-munin/freebox.py", line 4, in <module>
    import requests
  File "/usr/local/lib/python3.2/dist-packages/requests/__init__.py", line 64, in <module>
    from .models import Request, Response, PreparedRequest
  File "/usr/local/lib/python3.2/dist-packages/requests/models.py", line 856
    http_error_msg = u'%s Client Error: %s for url: %s' % (self.status_code, reason, self.url)
                                                      ^
SyntaxError: invalid syntax

```

**Comment by tikismoke** [comment]
tried with python 2.7 but got this:

```

root@munin:/home/Freebox-OS-munin# python2.7 ./main.py authorize
Authorizing...
Error while authenticating: {u'msg': u'Erreur interne', u'error_code': u'internal_error', u'success': False}

```

**Comment by chteuchteu** [comment]
At first sight, this error seems to come from the Python version you're using: http://stackoverflow.com/questions/38957513/hi-i-just-installed-requests-with-pip-but-i-cant-import-it

This script has only been tested with python 3.2.3 and 3.5.1. Which version are you using?

**Comment by tikismoke** [comment]
HOHO this time it works with python 2.7

```
root@munin:/home/Freebox-OS-munin# python3.2 --version
Python 3.2.3

```
Seems only the autorize process works with 2.7.
No time to test more this evening.

Could you have a look to make it works on python 2.7 for not so old debian :)

As always i could open you a ssh to test it but not this evening sorry.

**Comment by chteuchteu** [comment]
I'll check this soon! No need for any SSH access, I'll just have to install this specific version.

**Comment by chteuchteu** [comment]
I fixed python 2.7 compatibility in e3d9b8c. About the issue you're having when using `authorize` (`Error while authenticating: {u'msg': u'Erreur interne', u'error_code': u'internal_error', u'success': False}`), it seems to be an API error.

Are you still experiencing this issue?

**Comment by tikismoke** [comment]
Will look this evening or weekend.

Le 9 septembre 2016 18:29:23 GMT+02:00, Quentin Stoeckel <notifications@github.com> a écrit :
>I fixed python 2.7 compatibility in e3d9b8c. About the issue you're
>having when using `authorize` (`Error while authenticating: {u'msg':
>u'Erreur interne', u'error_code': u'internal_error', u'success':
>False}`), it seems to be an API error.
>
>Are you still experiencing this issue?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/chteuchteu/Freebox-OS-munin/issues/6#issuecomment-245965568

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by tikismoke** [comment]
Now all works very well on my debian 7 with python 2.7.3.

Very good job, well done.

**Comment by chteuchteu** [comment]
Awesome, thanks for the followup!
