### ISSUE TITLE
graph fan speed

### ISSUE THREAD

**Issue by tikismoke** [chteuchteu/Freebox-OS-munin#8]
To avoid othe person to have also this:
https://snag.gy/IRuQi1.jpg

We need to monitor and alert on fan speed:
https://snag.gy/5Iv2sL.jpg

A simple fan problems in fact :)

**Comment by chteuchteu** [comment]
Done! Currently testing it on my own Freebox

**Comment by tikismoke** [comment]
Thank's ;)

**Comment by chteuchteu** [comment]
Here it is!

![image](https://cloud.githubusercontent.com/assets/1551971/19821227/9101de74-9d5d-11e6-95c7-847cc9ff0926.png)

I'll wait for munin to properly populate the whole graph (like one and a half day) to post it in the readme
